# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('streetAddress', models.CharField(max_length=255, null=True)),
                ('addressLocality', models.CharField(max_length=100, null=True)),
                ('addressRegion', models.CharField(max_length=100, null=True)),
                ('addressCountry', models.CharField(max_length=100, null=True)),
                ('telephone', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openinghours', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('localbusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localbusiness.LocalBusiness')),
            ],
        ),
    ]
