# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localbusiness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localbusiness',
            name='additional_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
