# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localbusiness', '0004_auto_20170125_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openinghours',
            old_name='openinghours',
            new_name='opening_hours',
        ),
        migrations.AlterField(
            model_name='localbusiness',
            name='site_id',
            field=models.IntegerField(choices=[(1, 'unisport.dk'), (10, 'unisportstore.se'), (11, 'unisportstore.com'), (12, 'unisportstore.no'), (13, 'unisportstore.fi'), (14, 'unisportstore.nl'), (15, 'unisportstore.de'), (16, 'unisportstore.fr'), (20, 'unisportstore.be'), (21, 'unisportstore.ch'), (22, 'unisportstore.at'), (23, 'unisportstore.pl')]),
        ),
    ]
