# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localbusiness', '0006_auto_20170126_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localbusiness',
            name='additional_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='localbusiness',
            name='addressCountry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='localbusiness',
            name='addressLocality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='localbusiness',
            name='addressRegion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='localbusiness',
            name='postalCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='localbusiness',
            name='streetAddress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='localbusiness',
            name='telephone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
